version: "3"
services:
  ecofood:
    build: .
    restart: always
    volumes:
      - ./fr.techworks.ecofood:/var/www/html
      - ./fr.techworks.ecofood/vendor:/var/www/html/vendor
    ports:
      - 9000:80
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: ${DB_HOST}